In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyport.h:171:33: error: expected initializer before ‘Py_uintptr_t’
 typedef unsigned PY_LONG_LONG   Py_uintptr_t;
                                 ^
In file included from rect.cpp:8:0:
C:\Anaconda\include/pyconfig.h:302:23: error: ‘__int64’ does not name a type
 # define PY_LONG_LONG __int64
                       ^
C:\Anaconda\include/pyport.h:172:9: note: in expansion of macro ‘PY_LONG_LONG’
 typedef PY_LONG_LONG            Py_intptr_t;
         ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyport.h:185:9: error: ‘Py_intptr_t’ does not name a type
 typedef Py_intptr_t     Py_ssize_t;
         ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:107:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/object.h:111:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/object.h:111:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:137:20: error: ISO C++ forbids declaration of ‘Py_ssize_t’ with no type [-fpermissive]
 typedef Py_ssize_t (*lenfunc)(PyObject *);
                    ^
C:\Anaconda\include/object.h:137:20: error: typedef ‘Py_ssize_t’ is initialized (use decltype instead)
C:\Anaconda\include/object.h:137:22: error: ‘lenfunc’ was not declared in this scope
 typedef Py_ssize_t (*lenfunc)(PyObject *);
                      ^
C:\Anaconda\include/object.h:141:47: error: ‘Py_ssize_t’ has not been declared
 typedef PyObject *(*ssizeargfunc)(PyObject *, Py_ssize_t);
                                               ^
C:\Anaconda\include/object.h:142:52: error: ‘Py_ssize_t’ has not been declared
 typedef PyObject *(*ssizessizeargfunc)(PyObject *, Py_ssize_t, Py_ssize_t);
                                                    ^
C:\Anaconda\include/object.h:142:64: error: ‘Py_ssize_t’ has not been declared
 typedef PyObject *(*ssizessizeargfunc)(PyObject *, Py_ssize_t, Py_ssize_t);
                                                                ^
C:\Anaconda\include/object.h:145:43: error: ‘Py_ssize_t’ has not been declared
 typedef int(*ssizeobjargproc)(PyObject *, Py_ssize_t, PyObject *);
                                           ^
C:\Anaconda\include/object.h:146:48: error: ‘Py_ssize_t’ has not been declared
 typedef int(*ssizessizeobjargproc)(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *);
                                                ^
C:\Anaconda\include/object.h:146:60: error: ‘Py_ssize_t’ has not been declared
 typedef int(*ssizessizeobjargproc)(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *);
                                                            ^
C:\Anaconda\include/object.h:157:20: error: ISO C++ forbids declaration of ‘Py_ssize_t’ with no type [-fpermissive]
 typedef Py_ssize_t (*readbufferproc)(PyObject *, Py_ssize_t, void **);
                    ^
C:\Anaconda\include/object.h:157:20: error: typedef ‘Py_ssize_t’ is initialized (use decltype instead)
C:\Anaconda\include/object.h:157:22: error: ‘readbufferproc’ was not declared in this scope
 typedef Py_ssize_t (*readbufferproc)(PyObject *, Py_ssize_t, void **);
                      ^
C:\Anaconda\include/object.h:158:20: error: ISO C++ forbids declaration of ‘Py_ssize_t’ with no type [-fpermissive]
 typedef Py_ssize_t (*writebufferproc)(PyObject *, Py_ssize_t, void **);
                    ^
C:\Anaconda\include/object.h:158:20: error: typedef ‘Py_ssize_t’ is initialized (use decltype instead)
C:\Anaconda\include/object.h:158:22: error: ‘writebufferproc’ was not declared in this scope
 typedef Py_ssize_t (*writebufferproc)(PyObject *, Py_ssize_t, void **);
                      ^
C:\Anaconda\include/object.h:159:20: error: ISO C++ forbids declaration of ‘Py_ssize_t’ with no type [-fpermissive]
 typedef Py_ssize_t (*segcountproc)(PyObject *, Py_ssize_t *);
                    ^
C:\Anaconda\include/object.h:159:20: error: typedef ‘Py_ssize_t’ is initialized (use decltype instead)
C:\Anaconda\include/object.h:159:22: error: ‘segcountproc’ was not declared in this scope
 typedef Py_ssize_t (*segcountproc)(PyObject *, Py_ssize_t *);
                      ^
C:\Anaconda\include/object.h:160:20: error: ISO C++ forbids declaration of ‘Py_ssize_t’ with no type [-fpermissive]
 typedef Py_ssize_t (*charbufferproc)(PyObject *, Py_ssize_t, char **);
                    ^
C:\Anaconda\include/object.h:160:20: error: typedef ‘Py_ssize_t’ is initialized (use decltype instead)
C:\Anaconda\include/object.h:160:22: error: ‘charbufferproc’ was not declared in this scope
 typedef Py_ssize_t (*charbufferproc)(PyObject *, Py_ssize_t, char **);
                      ^
C:\Anaconda\include/object.h:167:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t len;
     ^
C:\Anaconda\include/object.h:168:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t itemsize;  /* This is Py_ssize_t so it can be
     ^
C:\Anaconda\include/object.h:173:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t *shape;
     ^
C:\Anaconda\include/object.h:174:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t *strides;
     ^
C:\Anaconda\include/object.h:175:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t *suboffsets;
     ^
C:\Anaconda\include/object.h:176:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t smalltable[2];  /* static store for shape and strides of
     ^
C:\Anaconda\include/object.h:276:5: error: ‘lenfunc’ does not name a type
     lenfunc sq_length;
     ^
C:\Anaconda\include/object.h:290:5: error: ‘lenfunc’ does not name a type
     lenfunc mp_length;
     ^
C:\Anaconda\include/object.h:296:5: error: ‘readbufferproc’ does not name a type
     readbufferproc bf_getreadbuffer;
     ^
C:\Anaconda\include/object.h:297:5: error: ‘writebufferproc’ does not name a type
     writebufferproc bf_getwritebuffer;
     ^
C:\Anaconda\include/object.h:298:5: error: ‘segcountproc’ does not name a type
     segcountproc bf_getsegcount;
     ^
C:\Anaconda\include/object.h:299:5: error: ‘charbufferproc’ does not name a type
     charbufferproc bf_getcharbuffer;
     ^
C:\Anaconda\include/object.h:322:54: error: ‘Py_ssize_t’ has not been declared
 typedef PyObject *(*allocfunc)(struct _typeobject *, Py_ssize_t);
                                                      ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/object.h:325:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/object.h:325:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:327:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t tp_basicsize, tp_itemsize; /* For allocation */
     ^
C:\Anaconda\include/object.h:372:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t tp_weaklistoffset;
     ^
C:\Anaconda\include/object.h:387:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t tp_dictoffset;
     ^
C:\Anaconda\include/object.h:450:60: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyType_GenericAlloc(PyTypeObject *, Py_ssize_t);
                                                            ^
In file included from C:\Anaconda\include/Python.h:81:0,
                 from rect.cpp:16:
C:\Anaconda\include/objimpl.h:152:66: error: ‘Py_ssize_t’ has not been declared
                                                  PyTypeObject *, Py_ssize_t);
                                                                  ^
C:\Anaconda\include/objimpl.h:154:60: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyVarObject *) _PyObject_NewVar(PyTypeObject *, Py_ssize_t);
                                                            ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/objimpl.h:235:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyGC_Collect(void);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:81:0,
                 from rect.cpp:16:
C:\Anaconda\include/objimpl.h:244:62: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyVarObject *) _PyObject_GC_Resize(PyVarObject *, Py_ssize_t);
                                                              ^
C:\Anaconda\include/objimpl.h:256:9: error: ‘Py_ssize_t’ does not name a type
         Py_ssize_t gc_refs;
         ^
C:\Anaconda\include/objimpl.h:308:63: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyVarObject *) _PyObject_GC_NewVar(PyTypeObject *, Py_ssize_t);
                                                               ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/unicodeobject.h:416:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:85:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:417:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t length;          /* Length of raw Unicode data in buffer */
     ^
C:\Anaconda\include/unicodeobject.h:466:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size             /* size of buffer */
     ^
C:\Anaconda\include/unicodeobject.h:472:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size       /* size of buffer */
     ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:490:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyUnicode_GetSize(
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:85:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:513:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length           /* New length */
     ^
C:\Anaconda\include/unicodeobject.h:563:50: error: ‘Py_ssize_t’ has not been declared
                                                  Py_ssize_t format_spec_len);
                                                  ^
C:\Anaconda\include/unicodeobject.h:576:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size             /* size of buffer */
     ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:591:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyUnicode_AsWideChar(
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:85:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:687:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size,            /* size of buffer */
     ^
C:\Anaconda\include/unicodeobject.h:697:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size,            /* number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:729:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:735:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:737:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t *consumed        /* bytes consumed */
     ^
C:\Anaconda\include/unicodeobject.h:742:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:752:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:758:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:760:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t *consumed                /* bytes consumed */
     ^
C:\Anaconda\include/unicodeobject.h:769:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:800:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:809:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:814:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t *consumed        /* bytes consumed */
     ^
C:\Anaconda\include/unicodeobject.h:842:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:874:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:883:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:888:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t *consumed                /* bytes consumed */
     ^
C:\Anaconda\include/unicodeobject.h:920:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:929:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:939:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length                   /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:946:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:956:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length                   /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:965:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,
     ^
C:\Anaconda\include/unicodeobject.h:977:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:987:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:999:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:1009:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:1037:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:1051:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:1072:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:1083:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,              /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:1089:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,          /* size of string */
     ^
C:\Anaconda\include/unicodeobject.h:1091:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t *consumed        /* bytes consumed */
     ^
C:\Anaconda\include/unicodeobject.h:1100:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,              /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:1132:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t length,                  /* Number of Py_UNICODE chars to encode */
     ^
C:\Anaconda\include/unicodeobject.h:1164:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t maxsplit         /* Maxsplit count */
     ^
C:\Anaconda\include/unicodeobject.h:1208:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t maxsplit         /* Maxsplit count */
     ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:1240:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyUnicode_Tailmatch(
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/unicodeobject.h:1252:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyUnicode_Find(
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/unicodeobject.h:1262:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyUnicode_Count(
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:85:0,
                 from rect.cpp:16:
C:\Anaconda\include/unicodeobject.h:1276:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t maxcount         /* Max. number of replacements to apply;
     ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/intobject.h:24:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:86:0,
                 from rect.cpp:16:
C:\Anaconda\include/intobject.h:36:55: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyInt_FromUnicode(Py_UNICODE*, Py_ssize_t, int);
                                                       ^
C:\Anaconda\include/intobject.h:40:42: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyInt_FromSsize_t(Py_ssize_t);
                                          ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/intobject.h:42:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyInt_AsSsize_t(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:86:0,
                 from rect.cpp:16:
C:\Anaconda\include/intobject.h:46:35: error: expected initializer before ‘PyInt_AsUnsignedLongLongMask’
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyInt_AsUnsignedLongLongMask(PyObject *);
                                   ^
C:\Anaconda\include/intobject.h:76:11: error: ‘Py_ssize_t’ has not been declared
           Py_ssize_t format_spec_len);
           ^
In file included from C:\Anaconda\include/Python.h:88:0,
                 from rect.cpp:16:
C:\Anaconda\include/longobject.h:22:43: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyLong_FromSsize_t(Py_ssize_t);
                                           ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/longobject.h:27:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyLong_AsSsize_t(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:88:0,
                 from rect.cpp:16:
C:\Anaconda\include/longobject.h:43:51: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(double) _PyLong_Frexp(PyLongObject *a, Py_ssize_t *e);
                                                   ^
In file included from rect.cpp:8:0:
C:\Anaconda\include/pyconfig.h:302:23: error: ‘__int64’ was not declared in this scope
 # define PY_LONG_LONG __int64
                       ^
C:\Anaconda\include/longobject.h:50:44: note: in expansion of macro ‘PY_LONG_LONG’
 PyAPI_FUNC(PyObject *) PyLong_FromLongLong(PY_LONG_LONG);
                                            ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyconfig.h:302:23: error: ‘__int64’ does not name a type
 # define PY_LONG_LONG __int64
                       ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/longobject.h:52:12: note: in expansion of macro ‘PY_LONG_LONG’
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLong(PyObject *);
            ^
In file included from C:\Anaconda\include/Python.h:88:0,
                 from rect.cpp:16:
C:\Anaconda\include/longobject.h:53:35: error: expected initializer before ‘PyLong_AsUnsignedLongLong’
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLong(PyObject *);
                                   ^
C:\Anaconda\include/longobject.h:54:35: error: expected initializer before ‘PyLong_AsUnsignedLongLongMask’
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLongMask(PyObject *);
                                   ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyconfig.h:302:23: error: ‘__int64’ does not name a type
 # define PY_LONG_LONG __int64
                       ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/longobject.h:55:12: note: in expansion of macro ‘PY_LONG_LONG’
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLongAndOverflow(PyObject *, int *);
            ^
In file included from C:\Anaconda\include/Python.h:88:0,
                 from rect.cpp:16:
C:\Anaconda\include/longobject.h:60:56: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyLong_FromUnicode(Py_UNICODE*, Py_ssize_t, int);
                                                        ^
C:\Anaconda\include/longobject.h:130:12: error: ‘Py_ssize_t’ has not been declared
            Py_ssize_t format_spec_len);
            ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/floatobject.h:15:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:89:0,
                 from rect.cpp:16:
C:\Anaconda\include/floatobject.h:128:13: error: ‘Py_ssize_t’ has not been declared
             Py_ssize_t format_spec_len);
             ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/complexobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:91:0,
                 from rect.cpp:16:
C:\Anaconda\include/complexobject.h:61:50: error: ‘Py_ssize_t’ has not been declared
                                                  Py_ssize_t format_spec_len);
                                                  ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/stringobject.h:36:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/stringobject.h:36:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:94:0,
                 from rect.cpp:16:
C:\Anaconda\include/stringobject.h:62:65: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyString_FromStringAndSize(const char *, Py_ssize_t);
                                                                 ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/stringobject.h:68:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyString_Size(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:94:0,
                 from rect.cpp:16:
C:\Anaconda\include/stringobject.h:73:47: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PyString_Resize(PyObject **, Py_ssize_t);
                                               ^
C:\Anaconda\include/stringobject.h:78:60: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyString_DecodeEscape(const char *, Py_ssize_t, 
                                                            ^
C:\Anaconda\include/stringobject.h:79:24: error: ‘Py_ssize_t’ has not been declared
          const char *, Py_ssize_t,
                        ^
C:\Anaconda\include/stringobject.h:105:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size,            /* size of buffer */
     ^
C:\Anaconda\include/stringobject.h:115:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t size,            /* number of chars to encode */
     ^
C:\Anaconda\include/stringobject.h:175:14: error: ‘Py_ssize_t’ does not name a type
     register Py_ssize_t *len /* pointer to length variable or NULL
              ^
C:\Anaconda\include/stringobject.h:175:26: error: ISO C++ forbids declaration of ‘len’ with no type [-fpermissive]
     register Py_ssize_t *len /* pointer to length variable or NULL
                          ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/stringobject.h:184:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) _PyString_InsertThousandsGroupingLocale(char *buffer,
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/stringobject.h:193:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) _PyString_InsertThousandsGrouping(char *buffer,
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:94:0,
                 from rect.cpp:16:
C:\Anaconda\include/stringobject.h:205:13: error: ‘Py_ssize_t’ has not been declared
             Py_ssize_t format_spec_len);
             ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/memoryobject.h:65:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:96:0,
                 from rect.cpp:16:
C:\Anaconda\include/bufferobject.h:20:44: error: ‘Py_ssize_t’ has not been declared
                                            Py_ssize_t offset, Py_ssize_t size);
                                            ^
C:\Anaconda\include/bufferobject.h:20:63: error: ‘Py_ssize_t’ has not been declared
                                            Py_ssize_t offset, Py_ssize_t size);
                                                               ^
C:\Anaconda\include/bufferobject.h:22:53: error: ‘Py_ssize_t’ has not been declared
                                                     Py_ssize_t offset,
                                                     ^
C:\Anaconda\include/bufferobject.h:23:53: error: ‘Py_ssize_t’ has not been declared
                                                     Py_ssize_t size);
                                                     ^
C:\Anaconda\include/bufferobject.h:25:55: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyBuffer_FromMemory(void *ptr, Py_ssize_t size);
                                                       ^
C:\Anaconda\include/bufferobject.h:26:64: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyBuffer_FromReadWriteMemory(void *ptr, Py_ssize_t size);
                                                                ^
C:\Anaconda\include/bufferobject.h:28:37: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyBuffer_New(Py_ssize_t size);
                                     ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/bytearrayobject.h:23:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/bytearrayobject.h:23:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:98:0,
                 from rect.cpp:16:
C:\Anaconda\include/bytearrayobject.h:26:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_alloc; /* How many bytes allocated */
     ^
C:\Anaconda\include/bytearrayobject.h:41:68: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyByteArray_FromStringAndSize(const char *, Py_ssize_t);
                                                                    ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/bytearrayobject.h:42:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyByteArray_Size(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:98:0,
                 from rect.cpp:16:
C:\Anaconda\include/bytearrayobject.h:44:48: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyByteArray_Resize(PyObject *, Py_ssize_t);
                                                ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/tupleobject.h:25:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/tupleobject.h:25:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:99:0,
                 from rect.cpp:16:
C:\Anaconda\include/tupleobject.h:40:36: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyTuple_New(Py_ssize_t size);
                                    ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/tupleobject.h:41:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyTuple_Size(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:99:0,
                 from rect.cpp:16:
C:\Anaconda\include/tupleobject.h:42:52: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyTuple_GetItem(PyObject *, Py_ssize_t);
                                                    ^
C:\Anaconda\include/tupleobject.h:43:45: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyTuple_SetItem(PyObject *, Py_ssize_t, PyObject *);
                                             ^
C:\Anaconda\include/tupleobject.h:44:53: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyTuple_GetSlice(PyObject *, Py_ssize_t, Py_ssize_t);
                                                     ^
C:\Anaconda\include/tupleobject.h:44:65: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyTuple_GetSlice(PyObject *, Py_ssize_t, Py_ssize_t);
                                                                 ^
C:\Anaconda\include/tupleobject.h:45:46: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PyTuple_Resize(PyObject **, Py_ssize_t);
                                              ^
C:\Anaconda\include/tupleobject.h:46:37: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyTuple_Pack(Py_ssize_t, ...);
                                     ^
C:\Anaconda\include/tupleobject.h:46:49: error: expected primary-expression before ‘...’ token
 PyAPI_FUNC(PyObject *) PyTuple_Pack(Py_ssize_t, ...);
                                                 ^
C:\Anaconda\include/tupleobject.h:46:52: error: expression list treated as compound expression in initializer [-fpermissive]
 PyAPI_FUNC(PyObject *) PyTuple_Pack(Py_ssize_t, ...);
                                                    ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/listobject.h:23:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/listobject.h:23:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:100:0,
                 from rect.cpp:16:
C:\Anaconda\include/listobject.h:38:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t allocated;
     ^
C:\Anaconda\include/listobject.h:47:35: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) PyList_New(Py_ssize_t size);
                                   ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/listobject.h:48:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyList_Size(PyObject *);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:100:0,
                 from rect.cpp:16:
C:\Anaconda\include/listobject.h:49:51: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyList_GetItem(PyObject *, Py_ssize_t);
                                                   ^
C:\Anaconda\include/listobject.h:50:44: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyList_SetItem(PyObject *, Py_ssize_t, PyObject *);
                                            ^
C:\Anaconda\include/listobject.h:51:43: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyList_Insert(PyObject *, Py_ssize_t, PyObject *);
                                           ^
C:\Anaconda\include/listobject.h:53:52: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyList_GetSlice(PyObject *, Py_ssize_t, Py_ssize_t);
                                                    ^
C:\Anaconda\include/listobject.h:53:64: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(PyObject *) PyList_GetSlice(PyObject *, Py_ssize_t, Py_ssize_t);
                                                                ^
C:\Anaconda\include/listobject.h:54:45: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyList_SetSlice(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *);
                                             ^
C:\Anaconda\include/listobject.h:54:57: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyList_SetSlice(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *);
                                                         ^
In file included from C:\Anaconda\include/Python.h:101:0,
                 from rect.cpp:16:
C:\Anaconda\include/dictobject.h:55:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t me_hash;
     ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/dictobject.h:71:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:101:0,
                 from rect.cpp:16:
C:\Anaconda\include/dictobject.h:72:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ma_fill;  /* # Active + # Dummy */
     ^
C:\Anaconda\include/dictobject.h:73:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ma_used;  /* # Active */
     ^
C:\Anaconda\include/dictobject.h:79:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ma_mask;
     ^
C:\Anaconda\include/dictobject.h:115:19: error: ‘Py_ssize_t’ has not been declared
     PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value);
                   ^
C:\Anaconda\include/dictobject.h:117:19: error: ‘Py_ssize_t’ has not been declared
     PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value, long *hash);
                   ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/dictobject.h:121:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PyDict_Size(PyObject *mp);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:101:0,
                 from rect.cpp:16:
C:\Anaconda\include/dictobject.h:125:44: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) _PyDict_NewPresized(Py_ssize_t minused);
                                            ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/setobject.h:36:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:103:0,
                 from rect.cpp:16:
C:\Anaconda\include/setobject.h:38:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t fill;  /* # Active + # Dummy */
     ^
C:\Anaconda\include/setobject.h:39:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t used;  /* # Active */
     ^
C:\Anaconda\include/setobject.h:45:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t mask;
     ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/setobject.h:85:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) PySet_Size(PyObject *anyset);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:103:0,
                 from rect.cpp:16:
C:\Anaconda\include/setobject.h:91:44: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PySet_Next(PyObject *set, Py_ssize_t *pos, PyObject **key);
                                            ^
C:\Anaconda\include/setobject.h:92:49: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PySet_NextEntry(PyObject *set, Py_ssize_t *pos, PyObject **key, long *hash);
                                                 ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/methodobject.h:82:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/funcobject.h:22:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/classobject.h:13:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/classobject.h:25:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/classobject.h:32:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/fileobject.h:11:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/cobject.h:79:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/traceback.h:13:2: note: in expansion of macro ‘PyObject_HEAD’
  PyObject_HEAD
  ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/sliceobject.h:23:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:112:0,
                 from rect.cpp:16:
C:\Anaconda\include/sliceobject.h:34:45: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) _PySlice_FromIndices(Py_ssize_t start, Py_ssize_t stop);
                                             ^
C:\Anaconda\include/sliceobject.h:34:63: error: ‘Py_ssize_t’ was not declared in this scope
 PyAPI_FUNC(PyObject *) _PySlice_FromIndices(Py_ssize_t start, Py_ssize_t stop);
                                                               ^
C:\Anaconda\include/sliceobject.h:34:78: error: expression list treated as compound expression in initializer [-fpermissive]
 PyAPI_FUNC(PyObject *) _PySlice_FromIndices(Py_ssize_t start, Py_ssize_t stop);
                                                                              ^
C:\Anaconda\include/sliceobject.h:35:54: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PySlice_GetIndices(PySliceObject *r, Py_ssize_t length,
                                                      ^
C:\Anaconda\include/sliceobject.h:36:35: error: ‘Py_ssize_t’ has not been declared
                                   Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step);
                                   ^
C:\Anaconda\include/sliceobject.h:36:54: error: ‘Py_ssize_t’ has not been declared
                                   Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step);
                                                      ^
C:\Anaconda\include/sliceobject.h:36:72: error: ‘Py_ssize_t’ has not been declared
                                   Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step);
                                                                        ^
C:\Anaconda\include/sliceobject.h:37:56: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PySlice_GetIndicesEx(PySliceObject *r, Py_ssize_t length,
                                                        ^
C:\Anaconda\include/sliceobject.h:38:9: error: ‘Py_ssize_t’ has not been declared
         Py_ssize_t *start, Py_ssize_t *stop, 
         ^
C:\Anaconda\include/sliceobject.h:38:28: error: ‘Py_ssize_t’ has not been declared
         Py_ssize_t *start, Py_ssize_t *stop, 
                            ^
C:\Anaconda\include/sliceobject.h:39:9: error: ‘Py_ssize_t’ has not been declared
         Py_ssize_t *step, Py_ssize_t *slicelength);
         ^
C:\Anaconda\include/sliceobject.h:39:27: error: ‘Py_ssize_t’ has not been declared
         Py_ssize_t *step, Py_ssize_t *slicelength);
                           ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/cellobject.h:10:2: note: in expansion of macro ‘PyObject_HEAD’
  PyObject_HEAD
  ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/genobject.h:13:2: note: in expansion of macro ‘PyObject_HEAD’
  PyObject_HEAD
  ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/descrobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD \
     ^
C:\Anaconda\include/descrobject.h:46:5: note: in expansion of macro ‘PyDescr_COMMON’
     PyDescr_COMMON;
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/descrobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD \
     ^
C:\Anaconda\include/descrobject.h:50:5: note: in expansion of macro ‘PyDescr_COMMON’
     PyDescr_COMMON;
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/descrobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD \
     ^
C:\Anaconda\include/descrobject.h:55:5: note: in expansion of macro ‘PyDescr_COMMON’
     PyDescr_COMMON;
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/descrobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD \
     ^
C:\Anaconda\include/descrobject.h:60:5: note: in expansion of macro ‘PyDescr_COMMON’
     PyDescr_COMMON;
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/descrobject.h:41:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD \
     ^
C:\Anaconda\include/descrobject.h:65:5: note: in expansion of macro ‘PyDescr_COMMON’
     PyDescr_COMMON;
     ^
In file included from C:\Anaconda\include/Python.h:117:0,
                 from rect.cpp:16:
C:\Anaconda\include/warnings.h:9:56: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyErr_WarnEx(PyObject *, const char *, Py_ssize_t);
                                                        ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/weakrefobject.h:16:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/weakrefobject.h:62:12: error: ‘Py_ssize_t’ does not name a type
 PyAPI_FUNC(Py_ssize_t) _PyWeakref_GetWeakrefCount(PyWeakReference *head);
            ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:10:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:17:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:31:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:121:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyerrors.h:37:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t start;
     ^
C:\Anaconda\include/pyerrors.h:38:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t end;
     ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:44:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:52:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/pyerrors.h:63:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:121:0,
                 from rect.cpp:16:
C:\Anaconda\include/pyerrors.h:246:33: error: ‘Py_ssize_t’ has not been declared
     const char *, const char *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                 ^
C:\Anaconda\include/pyerrors.h:246:45: error: ‘Py_ssize_t’ has not been declared
     const char *, const char *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                             ^
C:\Anaconda\include/pyerrors.h:246:57: error: ‘Py_ssize_t’ has not been declared
     const char *, const char *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                                         ^
C:\Anaconda\include/pyerrors.h:250:39: error: ‘Py_ssize_t’ has not been declared
     const char *, const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                       ^
C:\Anaconda\include/pyerrors.h:250:51: error: ‘Py_ssize_t’ has not been declared
     const char *, const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                                   ^
C:\Anaconda\include/pyerrors.h:250:63: error: ‘Py_ssize_t’ has not been declared
     const char *, const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                                               ^
C:\Anaconda\include/pyerrors.h:254:25: error: ‘Py_ssize_t’ has not been declared
     const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                         ^
C:\Anaconda\include/pyerrors.h:254:37: error: ‘Py_ssize_t’ has not been declared
     const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                     ^
C:\Anaconda\include/pyerrors.h:254:49: error: ‘Py_ssize_t’ has not been declared
     const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *);
                                                 ^
C:\Anaconda\include/pyerrors.h:267:59: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeEncodeError_GetStart(PyObject *, Py_ssize_t *);
                                                           ^
C:\Anaconda\include/pyerrors.h:268:59: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeDecodeError_GetStart(PyObject *, Py_ssize_t *);
                                                           ^
C:\Anaconda\include/pyerrors.h:269:62: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeTranslateError_GetStart(PyObject *, Py_ssize_t *);
                                                              ^
C:\Anaconda\include/pyerrors.h:273:59: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeEncodeError_SetStart(PyObject *, Py_ssize_t);
                                                           ^
C:\Anaconda\include/pyerrors.h:274:59: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeDecodeError_SetStart(PyObject *, Py_ssize_t);
                                                           ^
C:\Anaconda\include/pyerrors.h:275:62: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeTranslateError_SetStart(PyObject *, Py_ssize_t);
                                                              ^
C:\Anaconda\include/pyerrors.h:279:57: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeEncodeError_GetEnd(PyObject *, Py_ssize_t *);
                                                         ^
C:\Anaconda\include/pyerrors.h:280:57: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeDecodeError_GetEnd(PyObject *, Py_ssize_t *);
                                                         ^
C:\Anaconda\include/pyerrors.h:281:60: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeTranslateError_GetEnd(PyObject *, Py_ssize_t *);
                                                            ^
C:\Anaconda\include/pyerrors.h:285:57: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeEncodeError_SetEnd(PyObject *, Py_ssize_t);
                                                         ^
C:\Anaconda\include/pyerrors.h:286:57: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeDecodeError_SetEnd(PyObject *, Py_ssize_t);
                                                         ^
C:\Anaconda\include/pyerrors.h:287:60: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyUnicodeTranslateError_SetEnd(PyObject *, Py_ssize_t);
                                                            ^
In file included from C:\Anaconda\include/Python.h:126:0,
                 from rect.cpp:16:
C:\Anaconda\include/modsupport.h:30:61: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyArg_UnpackTuple(PyObject *, const char *, Py_ssize_t, Py_ssize_t, ...);
                                                             ^
C:\Anaconda\include/modsupport.h:30:73: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyArg_UnpackTuple(PyObject *, const char *, Py_ssize_t, Py_ssize_t, ...);
                                                                         ^
In file included from C:\Anaconda\include/Python.h:127:0,
                 from rect.cpp:16:
C:\Anaconda\include/pythonrun.h:177:46: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PyOS_URandom (void *buffer, Py_ssize_t size);
                                              ^
In file included from C:\Anaconda\include/Python.h:128:0,
                 from rect.cpp:16:
C:\Anaconda\include/ceval.h:147:48: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) _PyEval_SliceIndex(PyObject *, Py_ssize_t *);
                                                ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:421:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PyObject_Size(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:433:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PyObject_Length(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:436:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) _PyObject_LengthHint(PyObject *o, Py_ssize_t);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:133:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:478:43: error: ‘Py_ssize_t’ has not been declared
                                           Py_ssize_t *buffer_len);
                                           ^
C:\Anaconda\include/abstract.h:503:43: error: ‘Py_ssize_t’ has not been declared
                                           Py_ssize_t *buffer_len);
                                           ^
C:\Anaconda\include/abstract.h:519:44: error: ‘Py_ssize_t’ has not been declared
                                            Py_ssize_t *buffer_len);
                                            ^
C:\Anaconda\include/abstract.h:552:62: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(void *) PyBuffer_GetPointer(Py_buffer *view, Py_ssize_t *indices);
                                                              ^
C:\Anaconda\include/abstract.h:566:44: error: ‘Py_ssize_t’ has not been declared
                                            Py_ssize_t len, char fort);
                                            ^
C:\Anaconda\include/abstract.h:569:46: error: ‘Py_ssize_t’ has not been declared
                                              Py_ssize_t len, char fort);
                                              ^
C:\Anaconda\include/abstract.h:597:53: error: ‘Py_ssize_t’ has not been declared
                                                     Py_ssize_t *shape,
                                                     ^
C:\Anaconda\include/abstract.h:598:53: error: ‘Py_ssize_t’ has not been declared
                                                     Py_ssize_t *strides,
                                                     ^
C:\Anaconda\include/abstract.h:609:40: error: ‘Py_ssize_t’ has not been declared
                                        Py_ssize_t len, int readonly,
                                        ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:860:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PyNumber_AsSsize_t(PyObject *o, PyObject *exc);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:1055:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PySequence_Size(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:1064:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PySequence_Length(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:133:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:1077:60: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(PyObject *) PySequence_Repeat(PyObject *o, Py_ssize_t count);
                                                            ^
C:\Anaconda\include/abstract.h:1086:61: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(PyObject *) PySequence_GetItem(PyObject *o, Py_ssize_t i);
                                                             ^
C:\Anaconda\include/abstract.h:1093:62: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(PyObject *) PySequence_GetSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
                                                              ^
C:\Anaconda\include/abstract.h:1093:77: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(PyObject *) PySequence_GetSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
                                                                             ^
C:\Anaconda\include/abstract.h:1102:54: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_SetItem(PyObject *o, Py_ssize_t i, PyObject *v);
                                                      ^
C:\Anaconda\include/abstract.h:1111:54: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_DelItem(PyObject *o, Py_ssize_t i);
                                                      ^
C:\Anaconda\include/abstract.h:1119:55: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_SetSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2,
                                                       ^
C:\Anaconda\include/abstract.h:1119:70: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_SetSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2,
                                                                      ^
C:\Anaconda\include/abstract.h:1128:55: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_DelSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
                                                       ^
C:\Anaconda\include/abstract.h:1128:70: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(int) PySequence_DelSlice(PyObject *o, Py_ssize_t i1, Py_ssize_t i2);
                                                                      ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:1186:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PySequence_Count(PyObject *o, PyObject *value);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:1204:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) _PySequence_IterSearch(PyObject *seq,
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:1230:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PySequence_Index(PyObject *o, PyObject *value);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:133:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:1249:67: error: ‘Py_ssize_t’ has not been declared
      PyAPI_FUNC(PyObject *) PySequence_InPlaceRepeat(PyObject *o, Py_ssize_t count);
                                                                   ^
In file included from C:\Anaconda\include/Python.h:58:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:1269:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PyMapping_Size(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
C:\Anaconda\include/abstract.h:1279:17: error: ‘Py_ssize_t’ does not name a type
      PyAPI_FUNC(Py_ssize_t) PyMapping_Length(PyObject *o);
                 ^
C:\Anaconda\include/pyport.h:793:34: note: in definition of macro ‘PyAPI_FUNC’
 #       define PyAPI_FUNC(RTYPE) RTYPE
                                  ^
In file included from C:\Anaconda\include/Python.h:133:0,
                 from rect.cpp:16:
C:\Anaconda\include/abstract.h:1387:49: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(void) _Py_add_one_to_index_F(int nd, Py_ssize_t *index,
                                                 ^
C:\Anaconda\include/abstract.h:1388:47: error: ‘Py_ssize_t’ does not name a type
                                         const Py_ssize_t *shape);
                                               ^
C:\Anaconda\include/abstract.h:1388:59: error: ISO C++ forbids declaration of ‘shape’ with no type [-fpermissive]
                                         const Py_ssize_t *shape);
                                                           ^
C:\Anaconda\include/abstract.h:1389:49: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(void) _Py_add_one_to_index_C(int nd, Py_ssize_t *index,
                                                 ^
C:\Anaconda\include/abstract.h:1390:47: error: ‘Py_ssize_t’ does not name a type
                                         const Py_ssize_t *shape);
                                               ^
C:\Anaconda\include/abstract.h:1390:59: error: ISO C++ forbids declaration of ‘shape’ with no type [-fpermissive]
                                         const Py_ssize_t *shape);
                                                           ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/code.h:11:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD
     ^
In file included from C:\Anaconda\include/Python.h:140:0,
                 from rect.cpp:16:
C:\Anaconda\include/pystrcmp.h:8:61: error: ‘Py_ssize_t’ has not been declared
 PyAPI_FUNC(int) PyOS_mystrnicmp(const char *, const char *, Py_ssize_t);
                                                             ^
rect.cpp:369:46: error: ‘Py_ssize_t’ does not name a type
 typedef struct {PyObject **p; char *s; const Py_ssize_t n; const char* encoding;
                                              ^
rect.cpp:388:70: error: ‘Py_ssize_t’ has not been declared
 static CYTHON_INLINE char* __Pyx_PyObject_AsStringAndSize(PyObject*, Py_ssize_t* length);
                                                                      ^
rect.cpp:425:22: error: ‘Py_ssize_t’ does not name a type
 static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
                      ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
rect.cpp:547:3: note: in expansion of macro ‘PyObject_HEAD’
   PyObject_HEAD
   ^
rect.cpp:614:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/
     ^
rect.cpp:614:25: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/
                         ^
rect.cpp:614:45: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/
                                             ^
rect.cpp:619:42: error: ‘Py_ssize_t’ has not been declared
     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args, \
                                          ^
rect.cpp: In function ‘int __pyx_pw_4rect_11PyRectangle_1__cinit__(PyObject*, PyObject*, PyObject*)’:
rect.cpp:746:7: error: ‘Py_ssize_t’ was not declared in this scope
       Py_ssize_t kw_args;
       ^
rect.cpp:746:18: error: expected ‘;’ before ‘kw_args’
       Py_ssize_t kw_args;
                  ^
rect.cpp:747:13: error: ‘Py_ssize_t’ does not name a type
       const Py_ssize_t pos_args = PyTuple_GET_SIZE(__pyx_args);
             ^
rect.cpp:748:15: error: ‘pos_args’ was not declared in this scope
       switch (pos_args) {
               ^
rect.cpp:756:7: error: ‘kw_args’ was not declared in this scope
       kw_args = PyDict_Size(__pyx_kwds);
       ^
rect.cpp:756:39: error: ‘PyDict_Size’ was not declared in this scope
       kw_args = PyDict_Size(__pyx_kwds);
                                       ^
rect.cpp:757:15: error: ‘pos_args’ was not declared in this scope
       switch (pos_args) {
               ^
rect.cpp:778:91: error: ‘pos_args’ was not declared in this scope
         if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, pos_args, "__cinit__") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
                                                                                           ^
rect.cpp:511:45: note: in definition of macro ‘unlikely’
     #define unlikely(x) __builtin_expect(!!(x), 0)
                                             ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/tupleobject.h:51:33: note: in expansion of macro ‘Py_SIZE’
 #define PyTuple_GET_SIZE(op)    Py_SIZE(op)
                                 ^
rect.cpp:780:16: note: in expansion of macro ‘PyTuple_GET_SIZE’
     } else if (PyTuple_GET_SIZE(__pyx_args) != 4) {
                ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/tupleobject.h:51:33: note: in expansion of macro ‘Py_SIZE’
 #define PyTuple_GET_SIZE(op)    Py_SIZE(op)
                                 ^
rect.cpp:795:52: note: in expansion of macro ‘PyTuple_GET_SIZE’
   __Pyx_RaiseArgtupleInvalid("__cinit__", 1, 4, 4, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
                                                    ^
rect.cpp: In function ‘PyObject* __pyx_pf_4rect_11PyRectangle_4getLength(__pyx_obj_4rect_PyRectangle*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:932:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_r);
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:949:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_t_1);
   ^
rect.cpp: In function ‘PyObject* __pyx_pf_4rect_11PyRectangle_6getHeight(__pyx_obj_4rect_PyRectangle*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:995:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_r);
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:1012:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_t_1);
   ^
rect.cpp: In function ‘PyObject* __pyx_pf_4rect_11PyRectangle_8getArea(__pyx_obj_4rect_PyRectangle*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:1058:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_r);
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:1075:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_t_1);
   ^
rect.cpp: In function ‘PyObject* __pyx_pw_4rect_11PyRectangle_11move(PyObject*, PyObject*, PyObject*)’:
rect.cpp:1106:7: error: ‘Py_ssize_t’ was not declared in this scope
       Py_ssize_t kw_args;
       ^
rect.cpp:1106:18: error: expected ‘;’ before ‘kw_args’
       Py_ssize_t kw_args;
                  ^
rect.cpp:1107:13: error: ‘Py_ssize_t’ does not name a type
       const Py_ssize_t pos_args = PyTuple_GET_SIZE(__pyx_args);
             ^
rect.cpp:1108:15: error: ‘pos_args’ was not declared in this scope
       switch (pos_args) {
               ^
rect.cpp:1114:7: error: ‘kw_args’ was not declared in this scope
       kw_args = PyDict_Size(__pyx_kwds);
       ^
rect.cpp:1114:39: error: ‘PyDict_Size’ was not declared in this scope
       kw_args = PyDict_Size(__pyx_kwds);
                                       ^
rect.cpp:1115:15: error: ‘pos_args’ was not declared in this scope
       switch (pos_args) {
               ^
rect.cpp:1126:91: error: ‘pos_args’ was not declared in this scope
         if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, pos_args, "move") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
                                                                                           ^
rect.cpp:511:45: note: in definition of macro ‘unlikely’
     #define unlikely(x) __builtin_expect(!!(x), 0)
                                             ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/tupleobject.h:51:33: note: in expansion of macro ‘Py_SIZE’
 #define PyTuple_GET_SIZE(op)    Py_SIZE(op)
                                 ^
rect.cpp:1128:16: note: in expansion of macro ‘PyTuple_GET_SIZE’
     } else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
                ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/tupleobject.h:51:33: note: in expansion of macro ‘Py_SIZE’
 #define PyTuple_GET_SIZE(op)    Py_SIZE(op)
                                 ^
rect.cpp:1139:47: note: in expansion of macro ‘PyTuple_GET_SIZE’
   __Pyx_RaiseArgtupleInvalid("move", 1, 2, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
                                               ^
rect.cpp: In function ‘PyObject* __pyx_pf_4rect_11PyRectangle_10move(__pyx_obj_4rect_PyRectangle*, PyObject*, PyObject*)’:
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:593:27: note: in expansion of macro ‘Py_INCREF’
   #define __Pyx_INCREF(r) Py_INCREF(r)
                           ^
rect.cpp:1179:22: note: in expansion of macro ‘__Pyx_INCREF’
   __pyx_r = Py_None; __Pyx_INCREF(Py_None);
                      ^
rect.cpp: In function ‘PyObject* __pyx_tp_new_4rect_PyRectangle(PyTypeObject*, PyObject*, PyObject*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1199:5: note: in expansion of macro ‘Py_DECREF’
     Py_DECREF(o); o = 0;
     ^
rect.cpp: In function ‘void __pyx_tp_dealloc_4rect_PyRectangle(PyObject*)’:
C:\Anaconda\include/object.h:114:53: error: ‘PyObject’ has no member named ‘ob_refcnt’
 #define Py_REFCNT(ob)           (((PyObject*)(ob))->ob_refcnt)
                                                     ^
rect.cpp:1213:7: note: in expansion of macro ‘Py_REFCNT’
     ++Py_REFCNT(o);
       ^
C:\Anaconda\include/object.h:114:53: error: ‘PyObject’ has no member named ‘ob_refcnt’
 #define Py_REFCNT(ob)           (((PyObject*)(ob))->ob_refcnt)
                                                     ^
rect.cpp:1215:7: note: in expansion of macro ‘Py_REFCNT’
     --Py_REFCNT(o);
       ^
rect.cpp: At global scope:
rect.cpp:1286:1: error: too many initializers for ‘PyTypeObject {aka _typeobject}’
 };
 ^
rect.cpp:1286:1: error: invalid conversion from ‘int’ to ‘_typeobject*’ [-fpermissive]
rect.cpp:1286:1: error: cannot convert ‘const char*’ to ‘printfunc {aka int (*)(_object*, __sFILE64*, int)}’ in initialization
rect.cpp:1232:9: error: invalid conversion from ‘unsigned int’ to ‘getattrfunc {aka _object* (*)(_object*, char*)}’ [-fpermissive]
   sizeof(struct __pyx_obj_4rect_PyRectangle), /*tp_basicsize*/
         ^
rect.cpp:1286:1: error: invalid conversion from ‘void (*)(PyObject*) {aka void (*)(_object*)}’ to ‘cmpfunc {aka int (*)(_object*, _object*)}’ [-fpermissive]
 };
 ^
rect.cpp:1286:1: error: invalid conversion from ‘long int’ to ‘richcmpfunc {aka _object* (*)(_object*, _object*, int)}’ [-fpermissive]
rect.cpp:1286:1: error: cannot convert ‘PyMethodDef*’ to ‘descrgetfunc {aka _object* (*)(_object*, _object*, _object*)}’ in initialization
rect.cpp:1286:1: error: cannot convert ‘PyObject* (*)(PyTypeObject*, PyObject*, PyObject*) {aka _object* (*)(_typeobject*, _object*, _object*)}’ to ‘PyObject* {aka _object*}’ in initialization
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
 };
 ^
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1320:1: error: too many initializers for ‘__Pyx_StringTabEntry’
rect.cpp:1311:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_dx, __pyx_k_dx, sizeof(__pyx_k_dx), 0, 0, 1, 1},
                                     ^
rect.cpp:1312:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_dy, __pyx_k_dy, sizeof(__pyx_k_dy), 0, 0, 1, 1},
                                     ^
rect.cpp:1313:41: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_main, __pyx_k_main, sizeof(__pyx_k_main), 0, 0, 1, 1},
                                         ^
rect.cpp:1314:41: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_test, __pyx_k_test, sizeof(__pyx_k_test), 0, 0, 1, 1},
                                         ^
rect.cpp:1315:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_x0, __pyx_k_x0, sizeof(__pyx_k_x0), 0, 0, 1, 1},
                                     ^
rect.cpp:1316:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_x1, __pyx_k_x1, sizeof(__pyx_k_x1), 0, 0, 1, 1},
                                     ^
rect.cpp:1317:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_y0, __pyx_k_y0, sizeof(__pyx_k_y0), 0, 0, 1, 1},
                                     ^
rect.cpp:1318:37: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
   {&__pyx_n_s_y1, __pyx_k_y1, sizeof(__pyx_k_y1), 0, 0, 1, 1},
                                     ^
rect.cpp: In function ‘void initrect()’:
rect.cpp:1363:36: error: ‘PyTuple_New’ cannot be used as a function
   __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                    ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
C:\Anaconda\include/object.h:822:54: note: in expansion of macro ‘Py_INCREF’
 #define Py_XINCREF(op) do { if ((op) == NULL) ; else Py_INCREF(op); } while (0)
                                                      ^
rect.cpp:1383:93: note: in expansion of macro ‘Py_XINCREF’
   __pyx_m = Py_InitModule4(__Pyx_NAMESTR("rect"), __pyx_methods, 0, 0, PYTHON_API_VERSION); Py_XINCREF(__pyx_m);
                                                                                             ^
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:1389:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(__pyx_d);
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:594:27: note: in expansion of macro ‘Py_DECREF’
   #define __Pyx_DECREF(r) Py_DECREF(r)
                           ^
rect.cpp:1436:3: note: in expansion of macro ‘__Pyx_DECREF’
   __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:598:28: note: in expansion of macro ‘Py_XDECREF’
   #define __Pyx_XDECREF(r) Py_XDECREF(r)
                            ^
rect.cpp:1439:3: note: in expansion of macro ‘__Pyx_XDECREF’
   __Pyx_XDECREF(__pyx_t_1);
   ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1442:5: note: in expansion of macro ‘Py_DECREF’
     Py_DECREF(__pyx_m); __pyx_m = 0;
     ^
rect.cpp: At global scope:
rect.cpp:1475:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_min,
     ^
rect.cpp:1476:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_max,
     ^
rect.cpp:1477:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_found)
     ^
rect.cpp: In function ‘void __Pyx_RaiseArgtupleInvalid(const char*, int, int, int, int)’:
rect.cpp:1479:5: error: ‘Py_ssize_t’ was not declared in this scope
     Py_ssize_t num_expected;
     ^
rect.cpp:1479:16: error: expected ‘;’ before ‘num_expected’
     Py_ssize_t num_expected;
                ^
rect.cpp:1482:9: error: ‘num_expected’ was not declared in this scope
         num_expected = num_min;
         ^
rect.cpp:1485:9: error: ‘num_expected’ was not declared in this scope
         num_expected = num_max;
         ^
rect.cpp:1493:43: error: ‘num_expected’ was not declared in this scope
                  func_name, more_or_less, num_expected,
                                           ^
rect.cpp: At global scope:
rect.cpp:1515:5: error: ‘Py_ssize_t’ has not been declared
     Py_ssize_t num_pos_args,
     ^
rect.cpp: In function ‘int __Pyx_ParseOptionalKeywords(PyObject*, PyObject***, PyObject*, PyObject**, int, const char*)’:
rect.cpp:1519:5: error: ‘Py_ssize_t’ was not declared in this scope
     Py_ssize_t pos = 0;
     ^
rect.cpp:1519:16: error: expected ‘;’ before ‘pos’
     Py_ssize_t pos = 0;
                ^
rect.cpp:1522:31: error: ‘pos’ was not declared in this scope
     while (PyDict_Next(kwds, &pos, &key, &value)) {
                               ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/stringobject.h:92:32: note: in expansion of macro ‘Py_SIZE’
 #define PyString_GET_SIZE(op)  Py_SIZE(op)
                                ^
rect.cpp:1533:50: note: in expansion of macro ‘PyString_GET_SIZE’
                 if ((CYTHON_COMPILING_IN_PYPY || PyString_GET_SIZE(**name) == PyString_GET_SIZE(key))
                                                  ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/stringobject.h:92:32: note: in expansion of macro ‘Py_SIZE’
 #define PyString_GET_SIZE(op)  Py_SIZE(op)
                                ^
rect.cpp:1533:79: note: in expansion of macro ‘PyString_GET_SIZE’
                 if ((CYTHON_COMPILING_IN_PYPY || PyString_GET_SIZE(**name) == PyString_GET_SIZE(key))
                                                                               ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/stringobject.h:92:32: note: in expansion of macro ‘Py_SIZE’
 #define PyString_GET_SIZE(op)  Py_SIZE(op)
                                ^
rect.cpp:1545:58: note: in expansion of macro ‘PyString_GET_SIZE’
                             (CYTHON_COMPILING_IN_PYPY || PyString_GET_SIZE(**argname) == PyString_GET_SIZE(key))
                                                          ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/stringobject.h:92:32: note: in expansion of macro ‘Py_SIZE’
 #define PyString_GET_SIZE(op)  Py_SIZE(op)
                                ^
rect.cpp:1545:90: note: in expansion of macro ‘PyString_GET_SIZE’
                             (CYTHON_COMPILING_IN_PYPY || PyString_GET_SIZE(**argname) == PyString_GET_SIZE(key))
                                                                                          ^
rect.cpp: In function ‘int __Pyx_PyInt_As_int(PyObject*)’:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
rect.cpp:511:45: note: in definition of macro ‘unlikely’
     #define unlikely(x) __builtin_expect(!!(x), 0)
                                             ^
rect.cpp:1662:26: note: in expansion of macro ‘Py_SIZE’
             if (unlikely(Py_SIZE(x) < 0)) {
                          ^
rect.cpp:1613:33: error: ‘PyLong_AsUnsignedLongLong’ was not declared in this scope
         func_type value = func(x);                                        \
                                 ^
rect.cpp:1670:17: note: in expansion of macro ‘__PYX_VERIFY_RETURN_INT’
                 __PYX_VERIFY_RETURN_INT(int, unsigned long long, PyLong_AsUnsignedLongLong)
                 ^
rect.cpp:1613:33: error: ‘PyLong_AsLongLong’ was not declared in this scope
         func_type value = func(x);                                        \
                                 ^
rect.cpp:1687:17: note: in expansion of macro ‘__PYX_VERIFY_RETURN_INT’
                 __PYX_VERIFY_RETURN_INT(int, long long, PyLong_AsLongLong)
                 ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1701:17: note: in expansion of macro ‘Py_DECREF’
                 Py_DECREF(tmp);
                 ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1710:17: note: in expansion of macro ‘Py_DECREF’
                 Py_DECREF(v);
                 ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1722:9: note: in expansion of macro ‘Py_DECREF’
         Py_DECREF(tmp);
         ^
rect.cpp: In function ‘PyObject* __Pyx_PyInt_From_int(int)’:
rect.cpp:1742:57: error: ‘PyLong_FromLongLong’ cannot be used as a function
             return PyLong_FromLongLong((long long) value);
                                                         ^
rect.cpp: In function ‘PyObject* __Pyx_PyInt_From_long(long int)’:
rect.cpp:1768:57: error: ‘PyLong_FromLongLong’ cannot be used as a function
             return PyLong_FromLongLong((long long) value);
                                                         ^
rect.cpp: In function ‘long int __Pyx_PyInt_As_long(PyObject*)’:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
rect.cpp:511:45: note: in definition of macro ‘unlikely’
     #define unlikely(x) __builtin_expect(!!(x), 0)
                                             ^
rect.cpp:1814:26: note: in expansion of macro ‘Py_SIZE’
             if (unlikely(Py_SIZE(x) < 0)) {
                          ^
rect.cpp:1613:33: error: ‘PyLong_AsUnsignedLongLong’ was not declared in this scope
         func_type value = func(x);                                        \
                                 ^
rect.cpp:1822:17: note: in expansion of macro ‘__PYX_VERIFY_RETURN_INT’
                 __PYX_VERIFY_RETURN_INT(long, unsigned long long, PyLong_AsUnsignedLongLong)
                 ^
rect.cpp:1613:33: error: ‘PyLong_AsLongLong’ was not declared in this scope
         func_type value = func(x);                                        \
                                 ^
rect.cpp:1839:17: note: in expansion of macro ‘__PYX_VERIFY_RETURN_INT’
                 __PYX_VERIFY_RETURN_INT(long, long long, PyLong_AsLongLong)
                 ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1853:17: note: in expansion of macro ‘Py_DECREF’
                 Py_DECREF(tmp);
                 ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1862:17: note: in expansion of macro ‘Py_DECREF’
                 Py_DECREF(v);
                 ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1874:9: note: in expansion of macro ‘Py_DECREF’
         Py_DECREF(tmp);
         ^
rect.cpp: In function ‘PyCodeObject* __pyx_find_code_object(int)’:
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:1930:5: note: in expansion of macro ‘Py_INCREF’
     Py_INCREF(code_object);
     ^
rect.cpp: In function ‘void __pyx_insert_code_object(int, PyCodeObject*)’:
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:1947:13: note: in expansion of macro ‘Py_INCREF’
             Py_INCREF(code_object);
             ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:1955:9: note: in expansion of macro ‘Py_DECREF’
         Py_DECREF(tmp);
         ^
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:1974:5: note: in expansion of macro ‘Py_INCREF’
     Py_INCREF(code_object);
     ^
C:\Anaconda\include/frameobject.h: At global scope:
C:\Anaconda\include/object.h:80:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_refcnt;               \
     ^
C:\Anaconda\include/object.h:97:5: note: in expansion of macro ‘PyObject_HEAD’
     PyObject_HEAD                       \
     ^
C:\Anaconda\include/frameobject.h:17:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
C:\Anaconda\include/object.h:98:5: error: ‘Py_ssize_t’ does not name a type
     Py_ssize_t ob_size; /* Number of items in variable part */
     ^
C:\Anaconda\include/frameobject.h:17:5: note: in expansion of macro ‘PyObject_VAR_HEAD’
     PyObject_VAR_HEAD
     ^
rect.cpp: In function ‘PyCodeObject* __Pyx_CreateCodeObjectForTraceback(const char*, int, int, const char*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:2024:5: note: in expansion of macro ‘Py_DECREF’
     Py_DECREF(py_srcfile);
     ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:2025:5: note: in expansion of macro ‘Py_DECREF’
     Py_DECREF(py_funcname);
     ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:2028:5: note: in expansion of macro ‘Py_XDECREF’
     Py_XDECREF(py_srcfile);
     ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:2029:5: note: in expansion of macro ‘Py_XDECREF’
     Py_XDECREF(py_funcname);
     ^
rect.cpp: In function ‘void __Pyx_AddTraceback(const char*, int, int, const char*)’:
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:2056:5: note: in expansion of macro ‘Py_XDECREF’
     Py_XDECREF(py_code);
     ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
C:\Anaconda\include/object.h:823:54: note: in expansion of macro ‘Py_DECREF’
 #define Py_XDECREF(op) do { if ((op) == NULL) ; else Py_DECREF(op); } while (0)
                                                      ^
rect.cpp:2057:5: note: in expansion of macro ‘Py_XDECREF’
     Py_XDECREF(py_frame);
     ^
rect.cpp: In function ‘int __Pyx_InitStrings(__Pyx_StringTabEntry*)’:
rect.cpp:2064:51: error: ‘struct __Pyx_StringTabEntry’ has no member named ‘n’
             *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
                                                   ^
rect.cpp:2068:57: error: ‘struct __Pyx_StringTabEntry’ has no member named ‘n’
             *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
                                                         ^
rect.cpp: In function ‘char* __Pyx_PyObject_AsString(PyObject*)’:
rect.cpp:2094:5: error: ‘Py_ssize_t’ was not declared in this scope
     Py_ssize_t ignore;
     ^
rect.cpp:2094:16: error: expected ‘;’ before ‘ignore’
     Py_ssize_t ignore;
                ^
rect.cpp:2095:47: error: ‘ignore’ was not declared in this scope
     return __Pyx_PyObject_AsStringAndSize(o, &ignore);
                                               ^
rect.cpp: At global scope:
rect.cpp:2097:72: error: ‘Py_ssize_t’ has not been declared
 static CYTHON_INLINE char* __Pyx_PyObject_AsStringAndSize(PyObject* o, Py_ssize_t *length) {
                                                                        ^
In file included from C:\Anaconda\include/Python.h:80:0,
                 from rect.cpp:16:
rect.cpp: In function ‘char* __Pyx_PyObject_AsStringAndSize(PyObject*, int*)’:
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/bytearrayobject.h:50:70: note: in expansion of macro ‘Py_SIZE’
 #define PyByteArray_GET_SIZE(self)  (assert(PyByteArray_Check(self)),Py_SIZE(self))
                                                                      ^
rect.cpp:2142:19: note: in expansion of macro ‘PyByteArray_GET_SIZE’
         *length = PyByteArray_GET_SIZE(o);
                   ^
C:\Anaconda\include/object.h:116:56: error: ‘struct PyVarObject’ has no member named ‘ob_size’
 #define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                                        ^
C:\Anaconda\include/bytearrayobject.h:49:6: note: in expansion of macro ‘Py_SIZE’
      Py_SIZE(self) ? ((PyByteArrayObject *)(self))->ob_bytes : _PyByteArray_empty_string)
      ^
rect.cpp:2143:16: note: in expansion of macro ‘PyByteArray_AS_STRING’
         return PyByteArray_AS_STRING(o);
                ^
rect.cpp: In function ‘PyObject* __Pyx_PyNumber_Int(PyObject*)’:
C:\Anaconda\include/object.h:767:24: error: ‘PyObject’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
                        ^
rect.cpp:2171:12: note: in expansion of macro ‘Py_INCREF’
     return Py_INCREF(x), x;
            ^
C:\Anaconda\include/object.h:772:30: error: ‘PyObject’ has no member named ‘ob_refcnt’
         --((PyObject*)(op))->ob_refcnt != 0)            \
                              ^
rect.cpp:2197:7: note: in expansion of macro ‘Py_DECREF’
       Py_DECREF(res);
       ^
rect.cpp: At global scope:
rect.cpp:2212:22: error: ‘Py_ssize_t’ does not name a type
 static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
                      ^
error: command 'gcc' failed with exit status 1
